docs: update bad undo-add links
iterative/dvc.org pull request #1823
Opened 2020-09-29 06:05 UTC by jorgeorpinel

per https://github.com/iterative/dvc.org/runs/1179565776

2020-09-29 06:07 UTC, jorgeorpinel commented
p.s. should I also add a temporary redirect Ivan?

2020-09-29 06:09 UTC, jorgeorpinel commented
p.p.s. hey @jeremydesroches, how would we inspect how much traffic `dvc.org/doc/user-guide/updating-tracked-files`
 used to get? The Search Console says "URL is not on Google": https://search.google.com/u/1/search-console/inspect?resource_id=sc-domain%3Advc.org&id=1BHK2EaGld46LRxtSJ8TlA

2020-09-29 16:57 UTC, shcheklein commented
> p.s. should I also add a temporary redirect Ivan?

nah, I think we are fine here

CI checks are still broken ^^

2020-09-29 16:57 UTC, shcheklein requested changes
CI is broken

2020-09-29 20:02 UTC, jorgeorpinel commented on content/docs/command-reference/remove.md
> +Refer to [Updating Tracked Files](/doc/user-guide/how-to/updated-tracked-files)
```suggestion
Refer to [Updating Tracked Files](/doc/user-guide/how-to/update-tracked-files)
```

2020-09-29 20:02 UTC, jorgeorpinel commented on content/docs/command-reference/unprotect.md
> +[Update a Tracked File](/doc/user-guide/how-to/updated-tracked-files) guide to
```suggestion
[Update a Tracked File](/doc/user-guide/how-to/update-tracked-files) guide to
```

2020-09-29 20:02 UTC, jorgeorpinel commented on content/docs/user-guide/large-dataset-optimization.md
> +> [Update a Tracked File](/doc/user-guide/how-to/updated-tracked-files) guide to
```suggestion
> [Update a Tracked File](/doc/user-guide/how-to/update-tracked-files) guide to
```

2020-09-29 20:02 UTC, jorgeorpinel commented on content/docs/user-guide/large-dataset-optimization.md
> +[Update a Tracked File](/doc/user-guide/how-to/updated-tracked-files) on how to
```suggestion
[Update a Tracked File](/doc/user-guide/how-to/update-tracked-files) on how to
```

2020-09-29 20:04 UTC, jorgeorpinel commented
Sorry my bad... Typo 🤦 

BTW these new checks against the deployment app are great! Thanks @shcheklein @rogermparent

2020-09-29 20:15 UTC, shcheklein approved these changes

2020-09-29 20:15 UTC, merged

2020-10-01 14:30 UTC, jeremydesroches commented
> p.p.s. hey @jeremydesroches, how would we inspect how much traffic `dvc.org/doc/user-guide/updating-tracked-files`
> used to get? The Search Console says "URL is not on Google": https://search.google.com/u/1/search-console/inspect?resource_id=sc-domain%3Advc.org&id=1BHK2EaGld46LRxtSJ8TlA

The trick is to go into performance and then filter by the url. [This link](https://search.google.com/search-console/performance/search-analytics?resource_id=sc-domain%3Advc.org&page=*dvc.org%2Fdoc%2Fuser-guide%2Fupdating-tracked-files&num_of_months=12) should get you there on Search Console.

2020-10-01 19:43 UTC, jorgeorpinel commented
I see. Yeah I discovered that recently on Search Console actually. But this tells me how many impressions and clicks it gets, as well as the search queries, which is useful (screenshot below). But I was wondering even more general than that: the net traffic it gets, so should probably check in Google Analytics instead?

![image](https://user-images.githubusercontent.com/1477535/94855601-65d08500-03f4-11eb-9541-e79b0d7a5232.png)

2020-10-03 20:09 UTC, jeremydesroches commented
> the net traffic it gets, so should probably check in Google Analytics instead?

Yes. Usually the clicks will line up pretty well with sessions (for organic), but [try this view in Analytics](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a120072346w177588519p176254157/_u.date00=20190901&_u.date01=20201002&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:dvc.org~2Fdoc~2Fuser-guide~2Fupdating-tracked-files&_.useg=builtin5/).

2020-10-06 17:10 UTC, jorgeorpinel commented
Oh cool, thanks @jeremydesroches. Do you know if there's a way to add more than one page? I'd like to overlay that one with the new URL, dvc.org/doc/user-guide/how-to/update-tracked-files to see how smooth the transition was (there's a redirect form the previous one to this one).

2020-10-06 19:37 UTC, jeremydesroches commented
> Oh cool, thanks @jeremydesroches. Do you know if there's a way to add more than one page? I'd like to overlay that one with the new URL, dvc.org/doc/user-guide/how-to/update-tracked-files to see how smooth the transition was (there's a redirect form the previous one to this one).

Yep, try this [report in Analytics](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a120072346w177588519p176254157/_u.date00=20200801&_u.date01=20201006&_.useg=builtin5&explorer-table.filter=tracked-files&explorer-table.plotKeys=%5B%5B%22dvc.org~2Fdoc~2Fuser-guide~2Fhow-to~2Fupdate-tracked-files%22%5D,%5B%22dvc.org~2Fdoc~2Fuser-guide~2Fupdating-tracked-files%22%5D%5D/). You can also use [compare in Search Console](https://search.google.com/search-console/performance/search-analytics?resource_id=sc-domain%3Advc.org&page=!https%3A%2F%2Fdvc.org%2Fdoc%2Fuser-guide%2Fupdating-tracked-files&compare_page=https%3A%2F%2Fdvc.org%2Fdoc%2Fuser-guide%2Fhow-to%2Fupdate-tracked-files&num_of_months=3). 

I tried out the [original link](dvc.org/doc/user-guide/updating-tracked-files) and there doesn't seem to be a working redirect at the moment. It's good that the intent is to have a redirect, and I assume that will be fixed. This is actually a pretty important thing to handle for SEO purposes, so I'll just spell out what should happen in cases like this:

1. Publish the updated page at new url: `dvc.org/original-url` becomes `dvc.org/new-url`.
2. Create 301 redirect from `dvc.org/original-url` to `dvc.org/new-url`.
3. In Search Console, request indexing for `dvc.org/new-url`.
4. In Search Console, request indexing for `dvc.org/original-url` (so it picks up the redirect immediately).
5. Provided that new content is similar or better, organic traffic and ranking should transition seamlessly.

Hope this helps!

2020-10-06 19:40 UTC, jeremydesroches commented
> Yep, try this [report in Analytics](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a120072346w177588519p176254157/_u.date00=20200801&_u.date01=20201006&_.useg=builtin5&explorer-table.filter=tracked-files&explorer-table.plotKeys=%5B%5B%22dvc.org~2Fdoc~2Fuser-guide~2Fhow-to~2Fupdate-tracked-files%22%5D,%5B%22dvc.org~2Fdoc~2Fuser-guide~2Fupdating-tracked-files%22%5D%5D/). 

By the way, to produce that report: Find or search for the urls you want in the table, then check them off and select "Plot Rows".

2020-10-06 20:27 UTC, jorgeorpinel commented
Sweet! Looks like that search box takes regexps too, which is useful to find typos in links out there. I just fixed 2 old links that now cause 404s in old GitHub comments based on this:

![image](https://user-images.githubusercontent.com/1477535/95253580-3222a000-07e4-11eb-87cd-4aace805886f.png)

> I like that GA let's you look at weekly graphs too, which are much more smooth. If you find a way to do that in SC please lmk.

Page Compare on SC is also good but you can only have 2.

2020-10-06 20:33 UTC, jorgeorpinel commented
> This is actually a pretty important thing to handle for SEO purposes, so I'll just spell out what should happen

Actually we completely flopped on this this time. Not a big deal since we're talking about 100 visits/week but totally agree with those steps. We usually setup the redirects (which get removed later at some point) but we never reindex on SC — good tip, thanks.

I would add a step: to find any old links we have control of and update them, so the redirect can be removed later on.  We already do this in all the docs of course, since it's easy to grep the old URL, but they're also common in old GH comments, for example (maybe some 3rd party blogs we wrote?) which tend to not get updated.

2020-10-07 18:35 UTC, jeremydesroches commented
> Sweet! Looks like that search box takes regexps too, which is useful to find typos in links out there. I just fixed 2 old links that now cause 404s in old GitHub comments...

Nice @jorgeorpinel! Yes, you can do some amazing things with regexp in GA. Another spot I've used them is with Filters... easy to get carried away, but if you ever find visits coming in with strange event/channel/tag data, a regexp filter can clean everything up nicely. Only for data going forward though.

>  I like that GA let's you look at weekly graphs too, which are much more smooth. If you find a way to do that in SC please lmk.

> Page Compare on SC is also good but you can only have 2.

Yes, SC is pretty limited... BUT you can view SC data in GA if you [enable the connection](https://analytics.google.com/analytics/web/?authuser=0#/report/acquisition-sc-landingpages/a120072346w177588519p176254157/_u.date00=20200907&_u.date01=20201006&_.goalOption=ALL&_.useg=builtin1/)! Maybe you can get the best of both... 🙂

2020-10-07 18:53 UTC, jeremydesroches commented
> Actually we completely flopped on this this time. Not a big deal since we're talking about 100 visits/week but totally agree with those steps. We usually setup the redirects (which get removed later at some point) but we never reindex on SC — good tip, thanks.

Probably no harm done, as long as it's redirected relatively soon. The sitemap is likely being read daily, so new URLs will get picked up easily (e.g., a new blog post or doc will get indexed almost immediately). When URLs change it's a bit different: the 301 redirect assigns the previous URL's ranking to the new URL so takes its place in the index. Without a redirect the new URL _might_ be recognized as the old page, but could actually "start over". The old URL can hang around in the index for quite a while, too.

> I would add a step: to find any old links we have control of and update them, so the redirect can be removed later on. 

Yes, a very practice if the scope of your content allows for it. It's definitely better to have a well-maintained redirects file than hundreds of historical entries — but it happens. 😒

2020-10-07 22:47 UTC, jorgeorpinel commented
Thanks for the tips about Filters and on linking SC and GA @jeremydesroches, will check it out.

> Probably no harm done, as long as it's redirected relatively soon

Well, the change happened weeks ago already and as you may have noticed in the merged PR comment where I mentioned you, there was some damage done 😓 but if you want (and it can be good so you learn this) feel free to setup the redirect in [redirects-list.json](https://github.com/iterative/dvc.org/blob/master/redirects-list.json) with a small PR.