Replaced strong etags with HTTP ETags
iterative/dvc.org pull request #1852
Opened 2020-10-10 20:04 UTC by sarthakforwet

References #1730.

2020-10-11 21:01 UTC, jorgeorpinel commented
Hi @sarthakforwet does this PR intend to close #1730? If so please link them. See https://github.blog/2013-05-14-closing-issues-via-pull-requests/

2020-10-11 21:05 UTC, jorgeorpinel requested changes
Thanks @sarthakforwet but so far this looks like a grep-replace. It's a start but it's necessary to read the context around the change to see it makes sense please. Left a few specific instances but this is probably pervasive in all the changes. Please lmk when to review again.

2020-10-11 21:05 UTC, jorgeorpinel commented on content/docs/command-reference/import-url.md
> +| `http`   | HTTP to file with _HTTP ETag_\* | `https://example.com/path/to/data.csv`     |
No need to repeat "HTTP" here:
```suggestion
| `http`   | HTTP to file with _ETag_\* | `https://example.com/path/to/data.csv`     |
```
> Needs reformatting though.

2020-10-11 21:05 UTC, jorgeorpinel commented on content/docs/command-reference/import-url.md
> +  [HTTP ETag](https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation)
Same: We have "...of HTTP, HTTP eTag" with this change.

2020-10-11 21:05 UTC, jorgeorpinel commented on content/docs/user-guide/dvc-files-and-directories.md
>    for HTTP, S3, or Azure
Same. This reads "HTTP ETag for HTTP".

2020-10-12 12:36 UTC, sarthakforwet commented
> but this is probably pervasive in all the changes.

I also had the thought of changing the phrase according to surroundings but thought that it was necessary to add complete "HTTP ETag". Corrected now.

2020-10-13 01:20 UTC, shcheklein approved these changes

2020-10-14 22:14 UTC, jorgeorpinel approved these changes
Looks good now, thanks @sarthakforwet!

2020-10-14 22:14 UTC, merged