guide: consistency between pip and conda paks
iterative/dvc.org pull request #2396
Opened 2021-04-19 04:00 UTC by jorgeorpinel

rel https://github.com/iterative/dvc.org/pull/2336#pullrequestreview-622899490

Ended up being just small copy edits.

2021-04-20 00:29 UTC, shcheklein commented on content/docs/install/linux.md
> +plan to use, you might need to install optional dependencies: `-s3`, `-azure`,
why do we change this?

2021-04-20 00:29 UTC, shcheklein requested changes
Not sure I understand the reasoning for this PR. What is the context?

2021-04-26 05:25 UTC, jorgeorpinel commented
> What is the context?

@shcheklein It's a left-over from a recent regular updates PR (see https://github.com/iterative/dvc.org/pull/2336#pullrequestreview-622899490). At first I thought the docs were incorrect so I started changing this doc, but when **efiop** replied confirming docs are correct, I just left some style changes in the PR.

Specifically, for `pip` only package suffixes are listed (`[ssh]`, `[s3`], etc.) but for `conda` we have entire package names (`dvc-ssh`, `dvc-s3`, etc.) Alternatively I could change the `pip` paragraph to include the full package names (`dvc[ssh]`, etc.)

Obvi not a very important change, feel free to close it.

2021-04-26 20:55 UTC, shcheklein commented
> Specifically: For pip only package suffixes are listed ([ssh], [s3], etc.), but for conda we have entire package names (dvc-ssh, dvc-s3, etc.) Alternatively I could change the pip paragraph to include the full package names (dvc[ssh], etc.)

I think this is because for `conda` those are indeed independent packages, while for `pip` those are extensions to the main `dvc` package. For `pip` it's a well known convention, while for `conda` doing something like `-ssh` feels like we inventing one? Or may be it exists and I'm not familiar

2021-04-27 00:15 UTC, jorgeorpinel commented
TBH I'm not sure, I thought they were all technically separate packages (both on `pip` and `conda`). Let me just ask @efiop (👋) and close this for now then. Thanks

2021-04-27 00:15 UTC, closed without merging