dvclive - HuggingFace integration
iterative/dvc.org pull request #2718
Opened 2021-08-14 11:05 UTC by pacifikus

PR for the second task in iterative/dvclive#83

2021-08-14 11:31 UTC, daavoo requested changes
Thanks @pacifikus !. It looks like C.I. is failing. 

Could you try to run `yarn format-all` (More info at: https://dvc.org/doc/user-guide/contributing/docs#all-commands)

2021-08-14 17:59 UTC, pacifikus commented
> Thanks @pacifikus !. It looks like C.I. is failing.
> 
> Could you try to run `yarn format-all` (More info at: https://dvc.org/doc/user-guide/contributing/docs#all-commands)

Thanks, fixed

2021-08-16 07:17 UTC, daavoo approved these changes

2021-08-18 09:06 UTC, jorgeorpinel commented
This is waiting for https://github.com/iterative/dvclive/pull/137 right? Please lmk when to merge 🙂

2021-08-18 15:57 UTC, merged