http: remove digest option
iterative/dvc.org pull request #2802
Opened 2021-09-07 10:13 UTC by isidentical

We have removed the digest option in https://github.com/iterative/dvc/pull/6525

2021-09-07 11:18 UTC, efiop requested changes
Let's not remove it, but just clarify that it has been removed and put a link to a ticket in dvc repo, so people could give us feedback.

2021-09-09 23:23 UTC, jorgeorpinel commented
Agree to leave it for now with a note on which version it was removed but do we need to link to some GH ticket? I'd prefer to avoid that. Users can reach us via regular channels with feedback. Or is there a special reason we want to encourage feedback on this? Thanks

2021-09-10 08:33 UTC, efiop commented
@jorgeorpinel Just to have 1 place to point people to.

2021-10-01 18:20 UTC, jorgeorpinel commented on content/docs/command-reference/remote/modify.md
>    - `custom` - an additional HTTP header field will be set for all HTTP requests
Restoring per https://github.com/iterative/dvc.org/pull/2802#issuecomment-916507027
```suggestion
  - `digest` -
    [digest Access Authentication Scheme](https://tools.ietf.org/html/rfc7616).
    `user` and `password` (or `ask_password`) parameters should also be
    configured.
  - `custom` - an additional HTTP header field will be set for all HTTP requests
```

2021-10-01 18:23 UTC, jorgeorpinel submitted a review, later dismissed

2021-10-01 19:13 UTC, efiop approved these changes

2021-10-01 19:22 UTC, shcheklein commented
Was it deprecated or removed though?

2021-10-01 19:27 UTC, efiop commented
The difference is vague. I've suggested to include a link above, but that might be excessive. The current approach will work fine for now.

2021-10-01 20:38 UTC, shcheklein commented
Agreed on the link. It's more of a question - keep `deprecated` term or use `remove`. Even from the conversation you both have here:

`but just clarify that it has been _removed_`
`which version it was removed`
`We have removed the digest option`

it seems that it was removed? So, why don't explicitly say `removed in ...`

2021-10-04 22:15 UTC, jorgeorpinel commented
I changed to "removed".

I don't like the idea of linking to GH issues in general (seems fragile; we already have a few which are probably no longer relevant) but feel free to add the link to the appropriate ticket (I'm not sure which one @efiop referred to) and merge @isidentical.

2021-10-04 22:32 UTC, merged