`exp`: better explain experiment names in `--rev`
iterative/dvc.org pull request #3613
Opened 2022-06-02 03:10 UTC by jorgeorpinel

Follow-up to https://github.com/iterative/dvc.org/pull/3594#pullrequestreview-992934570

2022-06-03 14:07 UTC, pared requested changes

2022-06-03 14:07 UTC, pared commented on content/docs/api-reference/open.md
> +  a branch or tag name, commit hash, or [experiment name]). If `repo` is not a
No link for `[experiment name]`

2022-06-03 14:07 UTC, pared commented on content/docs/api-reference/read.md
> +  a branch or tag name, commit hash, or [experiment name]). If `repo` is not a
No link for `experiment name`

2022-06-11 19:15 UTC, jorgeorpinel commented on content/docs/api-reference/open.md
> +  a branch or tag name, commit hash, or [experiment name]). If `repo` is not a
Fixed

2022-06-11 19:15 UTC, jorgeorpinel commented on content/docs/api-reference/read.md
> +  a branch or tag name, commit hash, or [experiment name]). If `repo` is not a
Fixed

2022-06-11 19:16 UTC, jorgeorpinel commented
Sorry for delay @pared please approve + feel free to merge 🙂 or I will if you can't. Thanks

2022-06-20 23:53 UTC, jorgeorpinel commented
Ping @pared @dberenbaum 🙏🏼

2022-06-21 10:03 UTC, pared approved these changes

2022-06-21 10:03 UTC, pared commented
@jorgeorpinel sorry!

2022-06-21 10:05 UTC, merged

2022-06-21 22:59 UTC, jorgeorpinel commented
No worries, thanks!