Rephrased sentences containing "please"
iterative/dvc.org pull request #4249
Opened 2023-01-19 15:19 UTC by BhaswatiRoy

Fix: https://github.com/iterative/dvc.org/issues/3571

Rephrased all sentences in the documentation section that contained the "please" word into friendly sentences with similar meanings.

2023-01-24 15:23 UTC, omesser requested changes
Thanks @BhaswatiRoy !
lgtm 💯  - Just one typo

2023-01-24 15:35 UTC, BhaswatiRoy commented
Thanks for pointing out @omesser 
I have fixed the typo

2023-01-24 17:47 UTC, casperdcl approved these changes
thanks!

2023-01-25 22:28 UTC, casperdcl requested changes

2023-01-25 22:28 UTC, casperdcl commented on content/docs/install/index.md
> +  [these instructions](/doc/install/completion) to set it up
```suggestion
- Shell completion is automatically enabled by certain installation methods. If
  it does not work for you, see
  [these instructions](/doc/install/completion) to set it up.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/install/linux.md
> +> The shell configuration file needs to be restarted or re-sourced
```suggestion
> Restart your terminal, or re-source the shell configuration file
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/install/pre-release.md
>  [Development environment](/doc/user-guide/contributing/core#development-environment).
```suggestion
To install a development version for contributing to the project, see the
[Development environment](/doc/user-guide/contributing/core#development-environment)
guide.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/install/windows.md
> +by reviewing [Running DVC on Windows](/doc/user-guide/how-to/run-dvc-on-windows).
```suggestion
See [Running DVC on Windows](/doc/user-guide/how-to/run-dvc-on-windows)
for important tips to improve your experience on Windows.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/start/experiment-management/experiments.md
> +generate these files. You can refer to the documentation for more details.
redundant sentence

```suggestion
generate these files.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/start/experiment-management/experiments.md
> +For additional information, you can refer to
```suggestion
For more information, see the section on
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/get-started.md
> +sign up for the **Teams** or **Enterprise** plan, you can [schedule a call] (see
intentional

```suggestion
sign up for the **Teams** or **Enterprise** plan, please [schedule a call] (see
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/troubleshooting.md
> +If you need further help, feel free to send us a message using `Help` on the
```suggestion
If you need further help, you can send us a message using `Help` on the
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/troubleshooting.md
> +   If this solution does not work for your use case, don't hesitate to create a support
```suggestion
   If this solution does not work for your use case, please create a support
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/troubleshooting.md
> +not in the hidden commits list, then make sure to [raise a support request](#support).
```suggestion
not in the hidden commits list, please [raise a support request](#support).
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/troubleshooting.md
> +don't forget to check:
```suggestion
check that:
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/troubleshooting.md
> +If you get this error and none of the above applies, don't forget to
```suggestion
If you get this error and none of the above applies, please
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/troubleshooting.md
> +don't hesitate to [contact us](#support).
```suggestion
please [contact us](#support).
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/billing-and-payment.md
> +sign up for the **Teams** or **Enterprise** plan, feel free to [schedule a call] (see
```suggestion
sign up for the **Teams** or **Enterprise** plan, please [schedule a call] (see
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/billing-and-payment.md
> +about refunds, don't hesitate to [contact us].
```suggestion
about refunds, please [contact us].
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/billing-and-payment.md
> +To upgrade to or downgrade from Teams or Enterprise plan, feel free to [contact us].
```suggestion
To upgrade to or downgrade from Teams or Enterprise plan, please [contact us].
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/billing-and-payment.md
> +don't hesitate to [contact us].
```suggestion
please [contact us].
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/change-team-plan-and-size.md
> +the billing period. For inquiries about refunds, feel free to [contact us].
```suggestion
the billing period. For inquiries about refunds, please [contact us].
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/change-team-plan-and-size.md
> +For any changes to the plan, feel free to contact your focal point at Iterative.
```suggestion
For any changes to the plan, please ask your contact person at Iterative.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/change-team-plan-and-size.md
> +For any changes to the plan, don't hesitate to contact your focal point at Iterative.
```suggestion
For any changes to the plan, ask your contact person at Iterative.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/studio/user-guide/connect-custom-gitlab-server.md
> +you have any trouble setting up the connection to your GitLab server, feel free to
```suggestion
you have any trouble setting up the connection to your GitLab server, please
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/use-cases/index.md
> +tutorials. For more general, hands-on experience with DVC, you can head over to
```suggestion
tutorials. For more general, hands-on experience with DVC, see
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/use-cases/index.md
> +> in the community. Feel free to, [contact us](/support) if you need help or have
```suggestion
> in the community. [Contact us](/support) if you need help or have
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/use-cases/index.md
> +You can choose from the navigation sidebar to the left, or click the `Next`
```suggestion
Choose from the navigation sidebar to the left, or click the `Next`
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/use-cases/versioning-data-and-models/tutorial.md
>  to do so.
```suggestion
Also, [follow these instructions to install DVC](/doc/install) if it's not
already installed.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/use-cases/versioning-data-and-models/tutorial.md
>  > important tips to improve your experience.
```suggestion
> See [Running DVC on Windows](/doc/user-guide/how-to/run-dvc-on-windows)
> for important tips to improve your experience on Windows.
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/data-management/importing-external-data.md
> +Don't forget to check that you are able to connect both ways with tools like `ssh` and
```suggestion
Check that you can connect both ways with tools like `ssh` and
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/command-reference/remote/add.md
> +Do check whether you are able to connect both ways with tools like `ssh` and
```suggestion
Check that you can connect both ways with tools like `ssh` and
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/data-management/importing-external-data.md
> +> You may refer to `dvc remote modify` for more details like setting up access
```suggestion
> Refer to `dvc remote modify` for more details like setting up access
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/data-management/large-dataset-optimization.md
> +in order to protect the cache from corruption. You may refer to
```suggestion
in order to protect the cache from corruption. Refer to
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/data-management/managing-external-data.md
> +Don't forget to check that you are able to connect both ways with tools like `ssh` and
```suggestion
Check that you can connect both ways with tools like `ssh` and
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/data-management/managing-external-data.md
>  > Except for external data on different storage devices or partitions mounted on
```suggestion
> Exceptions to the above include: external data on different storage devices, and
partitions mounted on
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/data-management/managing-external-data.md
>  > external cache in that same drive to enable [file links] and avoid copying
```suggestion
> the same file system (e.g. `/mnt/raid/data`). In such cases, set up an
> external cache in the same drive to enable [file links] and avoid copying
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/how-to/run-dvc-on-windows.md
>  perfect solution, but here are some ideas:
```suggestion
DVC effectively, nor help you follow the examples in our docs. Here are some
alternatives:
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/how-to/run-dvc-on-windows.md
> +[Chocolatey](https://chocolatey.org/) (don't forget to install the tool first):
```suggestion
[Chocolatey](https://chocolatey.org). After installing Chocolatey, run:
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/how-to/setup-google-drive-remote.md
> +   > \* Do note the
```suggestion
   > \* Note the
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/how-to/setup-google-drive-remote.md
> +$ dvc remote modify myremote gdrive_acknowledge_abuse true
```suggestion
$ dvc remote modify myremote gdrive_acknowledge_abuse true
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/how-to/setup-google-drive-remote.md
> +> Don't forget to note our [Privacy Policy (Google APIs)](https://dvc.org/doc/user-guide/privacy).
```suggestion
> Note our [Privacy Policy (Google APIs)](https://dvc.org/doc/user-guide/privacy).
```

2023-01-25 22:28 UTC, casperdcl commented on content/docs/user-guide/troubleshooting.md
> +on Windows. Otherwise, you can try using a lower `JOBS` value.
```suggestion
on Windows. Otherwise, try using a lower `JOBS` value.
```

2023-01-25 22:39 UTC, casperdcl approved these changes

2023-01-25 23:00 UTC, merged

2023-02-03 06:29 UTC, jorgeorpinel commented
Thanks again @BhaswatiRoy and @casperdcl 🙏🏼