Studio Helm chart: mention system requirements
iterative/dvc.org pull request #4437
Opened 2023-03-27 13:59 UTC by jesper7

Add system requirements to the list of prerequisites in the installation guide for the Studio Helm chart.

2023-03-27 15:13 UTC, omesser requested changes

2023-03-27 15:13 UTC, omesser commented on content/docs/studio/self-hosting/installation/k8s-helm.md
> +
1. The requirements are not specific to the helm installation method, so should probably be here: https://github.com/iterative/dvc.org/blob/main/content/docs/studio/self-hosting/installation/index.md
2. storage requirements?

2023-04-10 00:05 UTC, omesser requested changes
@jesper7  - what about the 1st point from the previous [comment](https://github.com/iterative/dvc.org/pull/4437/files#r1149403915)
I think it makes sense to put the system requirements  either under self-hosting or self-hosting/installation, since they are common to all installation methods

2023-04-24 12:45 UTC, jesper7 commented
Closed in favor of https://github.com/iterative/dvc.org/pull/4474

2023-04-24 12:45 UTC, closed without merging