api-reference: Add `exp_show` and `scm`.
iterative/dvc.org pull request #4507
Opened 2023-05-02 11:29 UTC by daavoo

Per https://github.com/iterative/dvc/pull/9356

2023-05-02 14:38 UTC, dberenbaum commented on content/docs/sidebar.json
> +        "label": "scm"
Looks like you forgot `exp_show` here?

2023-05-02 14:40 UTC, dberenbaum commented on content/docs/api-reference/exp_show.md
> +- `revs` - List of Git commit (any
```suggestion
- `revs` - List of Git commits (any
```

2023-05-02 14:41 UTC, dberenbaum commented on content/docs/api-reference/exp_show.md
> +  not a Git repo, this option is ignored. _Default_: `None` (current working
When would `repo` not be a Git repo?

2023-05-02 14:49 UTC, dberenbaum commented on content/docs/api-reference/exp_show.md
> +up the rows:
I hope people can find uses for this on their own, but I wonder if cleaning up the table is the best example. You can do a lot of that from the CLI also. WDYT about an example like creating a new column with the difference between training and eval metrics? That's the kind of thing I would be likely to use it for. 

Not a blocker, just an idea to consider.

2023-05-02 14:51 UTC, dberenbaum requested changes
Thanks @daavoo! Looks like the sidebar is broken -- not sure if that's what's causing the link errors.

2023-05-02 16:51 UTC, omesser commented
released in [DVC 2.56.0](https://github.com/iterative/dvc/releases/tag/2.56.0)

2023-05-03 08:13 UTC, daavoo commented on content/docs/api-reference/exp_show.md
> +df.to_markdown()
```suggestion
df = pd.DataFrame(dvc.api.exp_show(), columns=columns)

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.to_markdown()
```

2023-05-03 17:03 UTC, dberenbaum commented on content/docs/api-reference/scm.md
> +tags = dvc.api.scm.all_tags()
Can we show example output here or in the example below?

2023-05-03 17:04 UTC, dberenbaum approved these changes
One minor suggestion. LGTM, thanks!

2023-05-15 08:32 UTC, merged