Show extension dag command in `start/data-management/data-pipelines`
iterative/dvc.org pull request #5093
Opened 2024-01-23 00:49 UTC by julieg18

## Demo

![Screenshot 2024-01-22 at 6 47 10 PM](https://github.com/iterative/dvc.org/assets/43496356/f26a06f7-b34c-4009-a400-43fb065beab8)

Fixes #4999

2024-01-23 00:59 UTC, julieg18 commented on content/docs/start/data-management/data-pipelines.md
> +
I chose a section with a gif, but open to other ideas/places!

2024-02-09 14:26 UTC, julieg18 commented
@dberenbaum, this pr has been sitting here for while, can you take a look when you have time?

2024-02-09 15:44 UTC, dberenbaum requested changes
Thanks for the ping @julieg18! Somehow this slipped by me.

What you added is fine, but I think it's more important to show how dvc.yaml support can help add and edit stages (using snippets, yaml schema hints, etc.). Do we have a video or gif for this? Could we show it above where we talk about adding stages?

2024-02-28 00:57 UTC, shcheklein commented
Closing it for now, let's get back to it later, when we have better idea about the get started structure.

2024-02-28 00:57 UTC, closed without merging