add an `install` section for DVClive
iterative/dvc.org pull request #5122
Opened 2024-02-13 15:29 UTC by AlexandreKempf

related to this discussion: https://iterativeai.slack.com/archives/CB41NAL8H/p1707823158357019

![image](https://github.com/iterative/dvc.org/assets/14785566/8c6bd91a-2533-482e-95e0-dc49c37990c6)

2024-02-13 16:23 UTC, dberenbaum requested changes
I think we are missing `[markdown]` here? Otherwise LGTM!

2024-02-13 19:25 UTC, shcheklein approved these changes

2024-02-13 20:43 UTC, AlexandreKempf commented
> I think we are missing `[markdown]` here? Otherwise LGTM!

Yeah fair point. To be honest, I'm not sure when you need to do a `[markdown]` install. Is that when you want to generate markdown reports?

2024-02-14 12:52 UTC, dberenbaum commented
> > I think we are missing `[markdown]` here? Otherwise LGTM!
> 
> Yeah fair point. To be honest, I'm not sure when you need to do a `[markdown]` install. Is that when you want to generate markdown reports?

Yup, it installs `matplotlib` and is used when `report` is `md` or `notebook`. See [here](https://github.com/iterative/dvclive/blob/aba880710a8cffac1fbb1ed07f974e36961277f3/src/dvclive/live.py#L314-L319).

2024-02-15 17:44 UTC, dberenbaum commented on content/docs/dvclive/install.md
> +- install `[markdown]` to use the [`make_report`]
```suggestion
- install `[markdown]` to use [`make_report`] when `report=md` or `report=notebook`
```

2024-02-15 17:44 UTC, dberenbaum approved these changes

2024-02-15 17:58 UTC, merged