feat: add platinum service support page
iterative/dvc.org pull request #5134
Opened 2024-02-19 17:00 UTC by yathomasi

- Added platinum service support page based on [document](https://github.com/iterative/dvc.ai/files/14281391/Platinum.Services.for.ML.Operations.1.pdf)

2024-02-19 17:04 UTC, yathomasi commented
@dberenbaum Feel free to suggest if you like to change anything.

2024-02-19 17:21 UTC, dberenbaum requested changes
Thanks @yathomasi!

Sorry, I should have earlier clarified one thing. We can drop the customer success stories and come back to this with https://github.com/iterative/dvc.ai/issues/70 when ready.

Otherwise LGTM, but I'll ask in Slack for GTM to also take a look.

2024-02-20 19:08 UTC, jendefig commented
This looks great @yathomasi!  @djsauble is working on a more prominent logo for DVC Enterprise Services.  We should put alt text on this so that it is searchable as an image when that's complete. 

I think some clarification needs to be made to the copy "keyboard support" if possible. cc: @joshcohen15 

And @dberenbaum's note about the customer success stories.

2024-02-21 11:51 UTC, yathomasi commented
<img width="1129" alt="Screenshot 2024-02-21 at 17 31 57" src="https://github.com/iterative/dvc.org/assets/20840228/afb80ff1-66fa-4aa4-a6c3-a54a03e8011a">

@jendefig Are you talking about these? If so, then that's great. These are quick icons I could find on the Icons list. Also, feel free to suggest topics, modules and text highlights.

I think it's also fine to publish as it and reiterate unless we want some big changes.

2024-02-21 13:37 UTC, dberenbaum approved these changes

2024-02-21 13:39 UTC, dberenbaum commented
Thanks @yathomasi! Agree that we can keep iterating after we publish.

2024-02-21 15:51 UTC, jendefig commented
> Are you talking about these? 
No, these icons look great!

I'm talking about having an actual image logo for DVC Enterprise Services with alt text attached to it so that when someone types it in google the image shows up and people can find and share it in UGC. It will also look better at the top of the page. 

"Platinum Services" like "Studio" are too common of phrases for anyone to find absent the connection with DVC.

2024-02-21 15:51 UTC, jendefig commented
But I'm also totally ok in moving forward and iterating in the interest of time.

2024-02-21 17:05 UTC, shcheklein commented
Good stuff. A bit unrelated.

Since top menu becomes crowded - can we drop the Other tools? It's really only VS Code. Make VS Code an icon nearby GitHub and Discord?

Later - can we merge Course, Community, etc at some point?

Also, do we show now anywhere our regular support channels? (just to clarify)

2024-02-21 17:14 UTC, jendefig commented
>Later - can we merge Course, Community, etc at some point?
Also, do we show now anywhere our regular support channels? (just to clarify)

The Community page needs some serious overhaul, but is where they are found.  I'm working towards it starting with finding more quotes. [See related](https://github.com/iterative/dvc.ai/issues/70). 
The other support channels can be arrived at through a button at the bottom.

2024-02-21 18:18 UTC, dberenbaum commented
@yathomasi It sounds like everyone is fine to merge and iterate.

@shcheklein The one support channel that gets completely "dropped" here is email.

2024-02-21 22:30 UTC, jendefig commented on src/components/Support/index.tsx
> +                knowledge and hands-on keyboard support enabled us to quickly
```suggestion
                knowledge and hands-on custom support enabled us to quickly
```

2024-02-21 22:36 UTC, jendefig approved these changes

2024-02-21 22:36 UTC, jendefig commented on src/components/Support/index.tsx
> +                knowledge and hands-on keyboard support enabled us to quickly
Per discussion on messaging of DVC Enterprise Services at today's GTM meeting, let's change this to "custom." cc: @joshcohen15 @dmpetrov

2024-02-22 03:51 UTC, merged

2024-02-22 04:30 UTC, tapadipti commented
Also, once there is some issue in the request quote form, it's not possible to close it even after fixing the issue. Eg, here, I tried to submit without the message. I could not close the form after that.


https://github.com/iterative/dvc.org/assets/32855442/f8d78145-84d1-4bd8-8be3-808996d34dec

2024-02-22 12:20 UTC, yathomasi commented
@tapadipti, Oops, silly mistake; I forgot to change the submitting state. I have quickly dropped a PR to fix that: https://github.com/iterative/dvc.org/pull/5145. 

Also, I am not sure about making the field `How we can help?` optional. People will have queries, concerns that they want to address. I think it should be fine. I added the `*` sign to show it's required so people will not get confused.

<img width="576" alt="Screenshot 2024-02-22 at 18 05 32" src="https://github.com/iterative/dvc.org/assets/20840228/b4715821-ce5c-4ace-a0fc-46184e17b6ad">

2024-02-22 12:56 UTC, tapadipti commented
> People will have queries, concerns that they want to address

Agreed. But some people might want to just discuss all that over all call instead of having to write it down beforehand. But it's ok if you strongly feel otherwise.

2024-02-22 13:13 UTC, yathomasi commented
> But some people might want to just discuss all that over all call instead of having to write it down beforehand. But it's ok if you strongly feel otherwise.

I hesitated a bit because I already proposed having `Calendly` so that users could directly setup meetings without having to fill out the form. But we agreed to use Hubspot, so I assumed we were looking to collect the data.

cc: @dberenbaum @jendefig Feel free to chime in and let me know if we want to make the field optional.

2024-02-22 14:14 UTC, dberenbaum commented
I agree with @tapadipti but will post in GTM to get other feedback

2024-02-22 15:16 UTC, skshetry commented
Hi, a minor feedback regarding the colors: I tried to click on them thinking they were links, as all three colors are closer to link colors for links and visited links.

I cannot tell what those three different colors mean, and some colors seem out of place (not sure why "experience" and "technical" are being colored, etc.)

2024-02-22 15:25 UTC, jendefig commented
I first tried to click on the links too like @skshetry.  I love color and think that they are mostly highlighting keywords that we would want to stand out.  There was one today I noticed that maybe should be colored but was not  -> scalability under the Best practices and standards heading and also 'standards' there as well. 

So maybe we add this to the next issue to update the logo when it's ready and make these corrections. 

It would also be super amazing to make content for these items that we could point to with links ultimately to prove these points. There are some we could do right now like "End to end solution" - Alex Kim's video. 🤔

2024-02-23 03:19 UTC, tapadipti commented
About making the `How can we help` field optional, [looks like it's ok to make that change](https://iterativeai.slack.com/archives/C02E3QJA6NB/p1708611388681819?thread_ts=1707916382.282139&cid=C02E3QJA6NB).

Re. colors, I agree with @skshetry at least on the blue color. Can we use a color other than blue? Imo, it's even better if we remove these colors and use a different style for highlighting - eg, make the text bold? Or use a single color for all these highlights, so that once a user finds out that one of them is not a link, they understand that all the others are also not links. For the ones that have content to link to, like @jendefig suggested, we can make them blue.

2024-02-23 06:53 UTC, yathomasi commented
Thanks to everyone for the review. I have created a separate ticket at https://github.com/iterative/dvc.org/issues/5152 for this issue. Feel free to add more if you have.